### ISSUE TITLE
Order-disorder model fails to build when VA is not an active component

### ISSUE THREAD

**Issue by richardotis** [richardotis/pycalphad#13]
This is the unit test failure:
```python
check_energy(Model(DBF, ['AL'], 'B2'), {v.T: 1400, v.SiteFraction('B2', 0, 'AL'): 1,
v.SiteFraction('B2', 1, 'AL'): 1}, -6.57639e4, mode='sympy')
```

```
======================================================================
ERROR: Pure component end-members in sympy mode.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rotis/.virtualenvs/calphad/lib/python3.3/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/rotis/git/pycalphad/pycalphad/tests/test_energy.py", line 298, in test_pure_sympy
    check_energy(Model(DBF, ['AL'], 'B2'), \
  File "/home/rotis/git/pycalphad/pycalphad/model.py", line 44, in __init__
    phase.upper(), dbe.symbols, dbe.search)
  File "/home/rotis/git/pycalphad/pycalphad/model.py", line 147, in build_phase
    symbols, param_search)
  File "/home/rotis/git/pycalphad/pycalphad/model.py", line 586, in atomic_ordering_energy
    molefraction_dict[sitefrac] = species_dict[sitefrac.species]
KeyError: 'VA'
```

This doesn't happen in the other models because they all check their contributions against Model.components to ensure that only active components are included.

**Comment by richardotis** [comment]
Looks like this is particular to phases with VA in a substitutional sublattice, but VA is not active.
